language: python

python:
    - '2.5'
    - '2.6'
    - '2.7'
    - 'pypy'

# Compile C library
before_install:
    - 'pushd .'
    - 'git clone -b v1.0.1 --depth 1 git://git.xiph.org/opus.git /tmp/opus'
    - 'cd /tmp/opus && ./autogen.sh && ./configure'
    - 'cd /tmp/opus && make && sudo make install'
    - 'popd'

# Install test dependencies
install:
    - 'sudo pip install pep8 --use-mirrors'

before_script:
    - 'pep8 --ignore=E501,E225 opus'
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.5" ]]; then sudo pip install unittest2 --use-mirrors; fi'
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then sudo pip install unittest2 --use-mirrors; fi'

script:
    - 'LD_PRELOAD=/usr/local/lib/libopus.so python setup.py test'